### ISSUE TITLE
404 Not Found Pop-up

### ISSUE THREAD

**Issue by codywarmbo** [kyuucr/add-link-to-qbittorrent-webui#10]
Hello, using this extension has been great. but recently since Qbittorrent updated I am unable to add magnet/torrent links from the right-click context menu. A pop-up appears saying 404 Not Found. 

Any solutions besides downgrading qBit? I upgraded out of necessity for some trackers.

**Comment by hiragashi** [comment]
I also have this same issue

**Comment by codywarmbo** [comment]
I've since discovered that qBit has a built-in method for handling magnet links. In the Web UI, you can click Tools in the menubar and register it. 
![image](https://user-images.githubusercontent.com/43068195/73593993-64e6fc80-44cf-11ea-9d36-5d243bcf34bd.png)

**Comment by kyuucr** [comment]
Should be fixed in the latest version 
Duplicate of #9
