### ISSUE TITLE
Request: support for multiple save paths

### ISSUE THREAD

**Issue by Ingvix** [kyuucr/add-link-to-qbittorrent-webui#2]
It'd be nice to have a submenu to context menu where you could choose from a few predetermined paths to save the torrent to. I have a few different paths that I often save my torrents so it's a bit irritating that I can use this addon only to save one of them.

**Comment by kyuucr** [comment]
Yeah I planned to do that, just don't have the time. My idea is that the configs would be separated by site url regex. So if a site url passed the regex, the predetermined config will be applied. Your idea will be easier to implement, but there will be submenu which means the submit action will take longer to reach.

**Comment by Ingvix** [comment]
Well, you could add an option for clicking to always open magnet links with this addon with selected config and also have the context menu entry with submenu for other configs to use.  Or to not have submenu but multiple entries in the main menu. Or make it optional which way the use wants it.

Regex would not work for me as usually one site might contains stuff that I would like to save in different paths.

**Comment by kyuucr** [comment]
Noted, I will put the submenu on my to-do list. I don't think I can rewrite
the clicking link behavior, so I won't implement that. Multiple main menu
feels cluttered but works, I will consider to add that option but that will
be low priority. There will be regex option but it can be disabled by
leaving it empty. For now the focus will be implementing sub menu.

**Comment by Ingvix** [comment]
Just thought it was a possibility as I tried "Bit Torrent WebUI"+ and "Torrent Control" addons and the first overwrites the magnet link click behavior fully to add it to selected torrent client and latter adds an entry to browser's own magnet handler where you can also set it to open magnet links automatically. Anyway, it's not that important feature but the submenu would really be appreciated. Hope you have time to implement it soon.

**Comment by kyuucr** [comment]
Pretty sure that both addons was legacy, now that we have webextensions some features and modifications are limited compared to legacy addons. For instance, Torrent Control now can't use the feature you've mentioned, on their addon page: 

> Web extension API doesn't (yet) support adding extensions to "What should Firefox do with this file" download dialog.

I'm more inclined to implement that download dialog than just hijacking the clicking event. I will consider adding that if Firefox implemented it.

**Comment by Ingvix** [comment]
Oh right. It was just me sticking with old legacy Firefox...

**Comment by simonbcn** [comment]
I think this could be easily implemented, see this extension for Transmission: https://addons.mozilla.org/es/firefox/addon/transmission-easy-client/
