### ISSUE TITLE
[Enhancement] Icon to access to webUI

### ISSUE THREAD

**Issue by simonbcn** [kyuucr/add-link-to-qbittorrent-webui#4]
Today I have installed `qBittorrent-nox` and this extension in Firefox. Both works great. But I miss a feature in this extension: an icon in toolbar to open the webUI.
I think it is easy to add this to extension and everyone can choose whether or not to put it and where to put it (_in the overflow menu or in the toolbar_).
Thanks for your work. :+1:

**Comment by kyuucr** [comment]
So, when you click the icon it opens a new tab and load the webUI site?

**Comment by simonbcn** [comment]
Yes, although in this case it is a little more complicated as each profile has its own URL and it can be different.
With one URL is easy.
`manifest.json`:
```
...
		"browser_action": {
			"browser_style": true,
			"default_icon": "icons/qbittorrent-tray.svg",
			"default_title": "qBittorrent WebUI"
		},
...
```
`background.js`:
```
...
browser.browserAction.onClicked.addListener((tab) => {
	 browser.tabs.create({"url": options["Default"].qbtUrl});
});
```

**Comment by kyuucr** [comment]
Well, that's how I'll implement it. If you have a code ready for that, I'll
be glad to merge it.

**Comment by simonbcn** [comment]
I've created a pull request. Warning, in that pull request is your README modified too. But I don't know how delete it from pull request.

**Comment by kyuucr** [comment]
Merged your PR, thanks!
