### ISSUE TITLE
Not working properly with qBittorrent 4.2

### ISSUE THREAD

**Issue by Ingvix** [kyuucr/add-link-to-qbittorrent-webui#9]
API seemed to have changed a bit with the new beta. Whenever I try to add a new torrent I get an error `Unacceptable file type, only regular file is allowed`.

**Comment by pellett655** [comment]
Same issue here.   Cannot add to WebUI through right-click menu with qBittorrent 4.2.0

**Comment by codywarmbo** [comment]
Similar issue, except I get 404 Not Found... when using right click to add a torrent/magnet.
